# jekyll theme (default: 'jekyll-theme-dinky')
theme: 'jekyll-theme-dinky'

docs:
  # title (default: 'C++ Competitive Programming Library')
  title: 'Docs by "online-judge-verify-helper"'
  # description (default: '')
  description: 'This documentation is generated automatically.'

  # show table-of-contents (default: False)
  toc: True

  # generate HTML as well as Markdown (default: False)
  html: False

  # show library files with categorizing (default: True)
  categorize_library: True
  # show verify files with categorizing (default: False)
  categorize_verify: False

# plugin (necessary for showing emoji)
plugins:
  - jemoji
