[package]
name = "aizu-online-judge"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
verification-helper-rust-example-hello = { path = "../../crates/hello" }
verification-helper-rust-example-world = { path = "../../crates/world" }
