name: test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install dependencies
      run: pip install .[dev]
    
    - name: Install boost
      run: sudo apt-get install libboost-all-dev
      if: matrix.os == 'ubuntu_latest'

    - name: Run tests
      run: |
        oj-verify -h
        python setup.py test
      shell: bash
